# Generated by Django 5.0.4 on 2024-04-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('A', 'Alta'), ('P', 'Pp'), ('B', 'Baja')], default='P', max_length=13),
        ),
    ]
